name: pix2poly
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - timm
    - pycocotools
    - albumentations
    - imageio
    - matplotlib-inline
    - opencv-python-headless
    - scikit-image
    - scikit-learn
    - scipy
    - shapely
    - imagecodecs
    - matplotlib
